<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_laser">
    
    <xacro:macro name='default_inertia' params='mass x:=0 y:=0 z:=0'>
        <inertial>
            <origin xyz='${x} ${y} ${z}'/>
            <mass value='${mass}'/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        </inertial>
    </xacro:macro>
    
    <xacro:macro name="robot_laser" params="x y z laser_size">

       <gazebo reference="laser_link">
          <material>Gazebo/Black</material>
       </gazebo>

        <link name="laser_link">
            <visual>
                <geometry>
                <cylinder radius="${laser_size/2}" length="${laser_size}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                <cylinder radius="${laser_size/2}" length="${laser_size}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <xacro:default_inertia mass="0.01"/>
        </link>

        <joint name="laser_joint" type="fixed">
            <parent link="base_link"/>
            <child link="laser_link"/>
            <origin rpy="0 0 0" xyz="${x} ${y} ${z}"/>
            <!--        <origin rpy="0 0 0" xyz="1.05 0 3"/>-->
        </joint>

        <gazebo reference="laser_link">
            <sensor type="ray" name="head_hokuyo_sensor">
                <pose>0 0 0 0 0 0</pose>
                <visualize>false</visualize>
                <update_rate>50</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>720</samples>
                            <resolution>1</resolution>
                            <min_angle>-1.570796</min_angle>
                            <max_angle>1.570796</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.10</min>
                        <max>10.0</max>
                        <resolution>0.01</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <!-- Noise parameters based on published spec for Hokuyo laser
                             achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                             stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                             reading. -->
                        <mean>0.0</mean>
                        <stddev>0.01</stddev>
                    </noise>
                </ray>
                <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                    <topicName>robot/scan</topicName>
                    <frameName>laser_link</frameName>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>